### PR TITLE
Make the short link provided to the user clickable

### PR DESCRIPTION
**Pull request by antithalian**
The suggestion of a clickable link in #3 seemed useful, so I updated client.js to make that work. I think that there's gotta a better way to add the `<a href></a>` element than what I did, which is updating the `innerHTML` attribute, so I'd be happy to figure out how to do that if desired.

Feel free to include this or not, whatever you want.

### CODE REVIEW

**Review by danerwilliams — CHANGES_REQUESTED** [review]
Looks good except could you change the styling so that it doesn't underline it? So looks same as originally but clickable.

**Comment by antithalian** [comment]
> 
> 
> Looks good except could you change the styling so that it doesn't underline it? So looks same as originally but clickable.

Sure, updated code on the way in a minute.

**Comment by antithalian** [comment]
Alright, got it updated. That should work anywhere, it's just adding a `text-decoration: none` to the style attribute.

**Review by danerwilliams — APPROVED** [review]
Lgtm!

**Pull request merged**
